FROM php:8.2-fpm

RUN apt-get update && apt-get install -y     git curl libpng-dev libonig-dev libxml2-dev zip unzip libjpeg-dev libfreetype6-dev

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd --with-freetype --with-jpeg     && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
USER root
